# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tom Casavant
email: tfcasavant@gmail.com
description: Open Source Programming
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tomcasavant.com" # the base hostname & protocol for your site
twitter_username: MrPresidentTom
github_username:  tomcasavant
paginate: 5
theme-dark: true #Set to true to change to dark website theme
permalink: /:title/

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
