# Site settings
title: Tom Casavant
description: >- # this means to ignore newlines until "baseurl:"
    Open Source Programming
baseurl: "/tomcasavant.github.io"  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repo: https://github.com/tomcasavant/tomcasavant.github.io


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Tom Casavant
  image    : https://ssl.gstatic.com/images/branding/product/1x/avatar_square_blue_512dp.png
  email    : tfcasavant@gmail.com
  github   : https://github.com/tomcasavant
  twitter  : https://twitter.com/mrpresidenttom
  linkedin : TODO
  facebook : TODO


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
