name: Eleventy Build
on:
  push:
    branches:
      - master
  schedule:
    - cron: "35 21 * * *"
  repository_dispatch:
   types: [dependency_update]
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
      GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install

      - name: Pull LFS files
        run: git lfs pull

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm ci

      - name: Eleventy
        run: DEBUG=Eleventy* npx @11ty/eleventy

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./dist
